name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      PG_DEV_DB_USER: postgres
      PG_DEV_DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
            pip install -r requirements/prod.txt
            pip install -r requirements/test.txt
            pip install -e .
      - name: Test
        run: |
            python -m pytest -v --cov-report term-missing --cov data_organizer data_organizer/test